#!/usr/bin/env bash
export DEBIAN_FRONTEND=noninteractive

echo ""
echo -e "=========================================="
echo -e "=== Setting up Ubuntu Virtual Machine  ==="
echo -e "=========================================="
echo ""
DBHOST=127.0.0.1
DBNAME=vagrantdb
DBUSER=vagrantsqluser
DBPASSWD=1FSPrxSbj5g4yFeEJ_P1Ork8D47seiAx

echo -e " > Updating packages"
sudo apt-get update -y >> /srv/dev/tmp/build.log 2>&1

echo -e " > Updating box"
sudo apt-get upgrade -y >> /srv/dev/tmp/build.log 2>&1

echo -e " > Installing mandatory packages"
sudo apt-get -y install vim curl build-essential python-software-properties git >> /srv/dev/tmp/build.log 2>&1
sudo apt-get -y -f install >> /srv/dev/tmp/build.log 2>&1

echo -e " > Setting up MariaDB"
echo -e "   > Pre-configuring MariaDB"
sudo debconf-set-selections <<< "mariadb-server-5.5 mysql-server/root_password password $DBPASSWD"
sudo debconf-set-selections <<< "mariadb-server-5.5 mysql-server/root_password_again password $DBPASSWD"
echo -e "   > Installing MariaDB"
sudo apt-get -y install mariadb-server >> /srv/dev/tmp/build.log 2>&1
echo -e "   > Configuring MariaDB"
mysql -uroot -p$DBPASSWD -e "CREATE DATABASE $DBNAME" >> /srv/dev/tmp/build.log 2>&1
mysql -uroot -p$DBPASSWD -e "grant all privileges on $DBNAME.* to '$DBUSER'@'localhost' identified by '$DBPASSWD'" >> /srv/dev/tmp/build.log 2>&1
sudo systemctl reload mysql >> /srv/dev/tmp/build.log 2>&1

echo -e " > Setting up PHPMyAdmin"
echo -e "   > Pre-configuring PHPMyAdmin"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean true" >> /srv/dev/tmp/build.log 2>&1
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/app-password-confirm password $DBPASSWD" >> /srv/dev/tmp/build.log 2>&1
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password $DBPASSWD" >> /srv/dev/tmp/build.log 2>&1
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-pass password $DBPASSWD" >> /srv/dev/tmp/build.log 2>&1
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect none" >> /srv/dev/tmp/build.log 2>&1
echo -e "   > Installing PHPMyAdmin"
sudo apt-get -qq install phpmyadmin >> /srv/dev/tmp/build.log 2>&1
sudo apt-get -y -f install >> /srv/dev/tmp/build.log 2>&1
echo -e "   > Configuring PHPMyAdmin"
mysql -uroot -p$DBPASSWD -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;" >> /srv/dev/tmp/build.log 2>&1
mysql -uroot -p$DBPASSWD -e "FLUSH PRIVILEGES;" > /srv/dev/tmp/build.log 2>&1


echo -e " > Configuring web-server"
echo -e "   > Installing nginx and php7.2"
sudo add-apt-repository ppa:ondrej/php >> /srv/dev/tmp/build.log 2>&1
sudo apt-get update -y >> /srv/dev/tmp/build.log 2>&1
sudo apt-get install -y nginx >> /srv/dev/tmp/build.log 2>&1
sudo apt-get install -y php7.2 php7.2-fpm php7.2-common php7.2-mbstring php7.2-xmlrpc php7.2-soap php7.2-gd php7.2-xml php7.2-intl php7.2-mysql php7.2-cli php7.2-zip php7.2-curl >> /srv/dev/tmp/build.log 2>&1

echo -e "   > Configuring nginx"
sudo rm /etc/nginx/sites-available/default
sudo cp /srv/dev/config/nginx/default /etc/nginx/sites-available/default

echo -e "   > Restarting nginx"
sudo service nginx restart >> /srv/dev/tmp/build.log 2>&1
echo -e "   > Restarting php"
sudo service php7.2-fpm restart >> /srv/dev/tmp/build.log 2>&1

echo -e " > Creating index.html"
sudo rm /srv/dev/app/index.html >> /srv/dev/tmp/build.log 2>&1
sudo touch /srv/dev/app/index.html >> /srv/dev/tmp/build.log 2>&1
sudo cat >> /srv/dev/app/index.html <<'EOF'
    <!DOCTYPE html>
    <html>
        <head>
        </head>
        <body>
            Hello World
        </body>
    </html>
EOF

echo -e " > Server is ready"
echo -e "   > Use vagrant ssh to access server"
echo -e "   > Website is available at: svetaine.test"
echo -e "   > PHPMyAdmin is avaialbe at: phpmyadmin.test"
echo -e "     > Login information:"
echo -e "       > Username: $DBUSER"
echo -e "       > Username: $DBPASSWD"
echo -e "   > Your website resides in app/ folder"
echo -e "     Edit or place your files there to update the website"
echo ""